### ISSUE TITLE
IAM

### ISSUE THREAD

**Issue by yagonobre** [kz8s/tack#102]
@wellsie you plan to add IAM to tack?

**Comment by wellsie** [comment]
I'm not sure what the ask is...

**Comment by adambom** [comment]
I was just about to create an issue regarding authentication, which @yagonobre may be trying to get at. My goal would be to set up as system by which we could tie IAM accounts to user accounts in Kubernetes. I'll go ahead and create that ticket and link to it here.

**Comment by adambom** [comment]
Tagging #106
