### ISSUE TITLE
Unify tags' name KubernetesCluster and Cluster

### ISSUE THREAD

**Issue by fuyufjh** [kz8s/tack#108]
I found a little problem when I created Resource Group for many k8s cluster in AWS. Most resources have tag `KubernetesCluster:cluster-name`, while Route53, S3 and Security Group have tag `Cluster:cluster-name`.

Could we unify these things, saying, all resources tagged with `KubernetesCluster:cluster-name`?

Willing to send PR fixing this :)

**Comment by wellsie** [comment]
Yes, please send pr
