### ISSUE TITLE
Adding some additional functionality to tack, such as more logging options, monitoring, etc.

### ISSUE THREAD

**Issue by ndbroadbent** [kz8s/tack#11]
Hi, I'm just tweaking a few things and wondering if they might be useful to other people. I think we're getting kind of close to a Heroku-out-of-the-box on AWS, so was wondering if it might be something you that interests you?

One thing I don't really like is only having logs in CloudWatch, because then I can't read any logs in the k8s dashboard or on the command line. So I'm also installing:
- [Logging with ElasticSearch and Kibana](http://kubernetes.io/docs/getting-started-guides/logging-elasticsearch/)
- [Heapster (InfluxDB and Grafana)](https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md)
- [Flocker](https://github.com/kubernetes/kubernetes/tree/release-1.2/examples/flocker/) for managing data volumes
- [Deis Workflow](https://github.com/deis/workflow/blob/master/src/installing-workflow/installing-deis-workflow.md)

Also happy to leave it as it is for now and just add these things to my own fork :)

**Comment by wellsie** [comment]
Hey Nathan. Yes all these things are of interest!! I had Kibana and ES up at one point but opted to start with CloudWatch since there wasn’t an example of it that I could fine. I agree though not having logs in the dashboard is a pain.

**Comment by ndbroadbent** [comment]
Ok great! I'm actually finding it really hard to port over fluentd and elasticsearch from the [kubernetes setup scripts](https://github.com/kubernetes/kubernetes/tree/master/cluster). I figured out where to copy the manifests to set up elasticsearch and kibana, but don't know where to put the fluentd stuff so that runs in every container.

**Comment by wellsie** [comment]
I'll had it working a couple of months ago. I'll take a look tomorrow.

**Comment by wellsie** [comment]
@ndbroadbent take a look at #13 ([commit](https://github.com/kz8s/tack/commit/a3cd2df44c5556e64b20c2b62557e2692479ea42)). I pulled CloudWatch logging and added fluentd (daemonset), elasticsearch and kibana. Will merge to master once I've had time to test more. lmk how it goes for you.
