### ISSUE TITLE
Bastion etcd config - old s3 downloader + no CA.

### ISSUE THREAD

**Issue by jasisk** [kz8s/tack#112]
Hi there,

Happy to open a PR but just wanted to validate the problem first. Seems the bastion cannot connect to the etcd2 cluster because it's missing the CA. This keeps it from being able to issue the lock in order to update itself.

Additionally, it appears to still have to old s3 downloader script (as opposed to the go binary).

**Comment by wellsie** [comment]
hi @jasisk - yeah the bastion has been neglected. It just needs to be brought up to par with the master/worker nodes.

**Comment by jasisk** [comment]
Perfect. Just the validation I need. :grinning:

I'll take a crack at fixing. Leaving this open until then.

**Comment by wellsie** [comment]
awesome - ty

**Comment by grncdr** [comment]
@jasisk did you have a chance to look into this? I'm noticing the same issue on a fresh cluster.

**Comment by grncdr** [comment]
For the benefit of others doing Google searches, my logs on the bastion host look like this:

```
$ journalctl -f
Dec 29 15:23:52 ip-10-0-0-28.eu-central-1.compute.internal etcd2[1116]: proxy: could not retrieve cluster information from the given urls
Dec 29 15:23:53 ip-10-0-0-28.eu-central-1.compute.internal etcd2[1116]: could not get cluster response from https://etcd1.tack-farm.kz8s:2380: Get https://etcd1.tack-test.kz8s:2380/members: x509: certificate signed by unknown authority
Dec 29 15:23:53 ip-10-0-0-28.eu-central-1.compute.internal etcd2[1116]: could not get cluster response from https://etcd2.tack-farm.kz8s:2380: Get https://etcd2.tack-test.kz8s:2380/members: x509: certificate signed by unknown authority
Dec 29 15:23:53 ip-10-0-0-28.eu-central-1.compute.internal etcd2[1116]: could not get cluster response from https://etcd3.tack-farm.kz8s:2380: Get https://etcd3.tack-test.kz8s:2380/members: x509: certificate signed by unknown authority
```

**Comment by jasisk** [comment]
> did you have a chance to look into this?

I did. Fixed it locally. Let me clean up what I have and rebase it.

**Comment by grncdr** [comment]
@jasisk I ended up fixing it myself as well (see PR above). It was a good opportunity for me to learn more about how the different parts of `tack` work together.

**Comment by wellsie** [comment]
no longer using s3 for shipping around certs
