### ISSUE TITLE
Add a warning to readme about terraform v0.7.10-0.7.11

### ISSUE THREAD

**Issue by jasisk** [kz8s/tack#115]
Just wanted to point out that terraform v0.7.10 and v0.7.11 seem to have a regression resulting in the cloud-config templates not rendering. Figured I'd point it out before you start getting related issues filed.

Someone has already [file an issue upstream](https://github.com/hashicorp/terraform/issues/10209).

**Comment by unguiculus** [comment]
PR #114, which I just created today, fixes the issue using data sources instead of template_file resources which are deprecated anyways.

**Comment by jasisk** [comment]
Ack. My search terms weren't very good, it seems. :) closing in favor of #111, #114.
