### ISSUE TITLE
Errors when running `make clean` to tear down cluster

### ISSUE THREAD

**Issue by ndbroadbent** [kz8s/tack#12]
This has been consistently happening the last few times I run `make clean`:

```
Error applying plan:

3 error(s) occurred:

* aws_subnet.public.1: Error deleting subnet: timeout while waiting for state to become '[destroyed]'
* aws_subnet.public.2: Error deleting subnet: timeout while waiting for state to become '[destroyed]'
* aws_internet_gateway.main: Error waiting for internet gateway (igw-3e7f795b) to detach: couldn't find resource

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
make: *** [destroy] Error 1
```

**Comment by wellsie** [comment]
I don’t recall having seen that myself. Does punching `make clean` again work ?

**Comment by ndbroadbent** [comment]
Nope I still get the same error. I think it's due to some network interfaces not being detached properly. Once I detach and delete those, the `make clean` is successful. Maybe this is a bug in terraform?

**Comment by wellsie** [comment]
Does it happen every time ? I spin up and tear down clusters several times a day and haven't seen it yet.  Are you running 'make clean' right after 'make all' ?

**Comment by ndbroadbent** [comment]
Ohhh I figured it out, Deis Workflow automatically provisions an extra load balancer. So I just needed to delete that first.
