### ISSUE TITLE
Make all fails with below error, while trying to create a cluster using existing vpc.

### ISSUE THREAD

**Issue by JayBee6** [kz8s/tack#122]
terraform get
Get: file:///Users/jrajagopal/Documents/repos/kubernetesconfig/modules/s3
Get: file:///Users/jrajagopal/Documents/repos/kubernetesconfig/modules/vpc-existing
Get: file:///Users/jrajagopal/Documents/repos/kubernetesconfig/modules/security
Get: file:///Users/jrajagopal/Documents/repos/kubernetesconfig/modules/iam
Get: file:///Users/jrajagopal/Documents/repos/kubernetesconfig/modules/route53
Get: file:///Users/jrajagopal/Documents/repos/kubernetesconfig/modules/etcd
Get: file:///Users/jrajagopal/Documents/repos/kubernetesconfig/modules/bastion
Get: file:///Users/jrajagopal/Documents/repos/kubernetesconfig/modules/worker
Get: file:///Users/jrajagopal/Documents/repos/kubernetesconfig/modules/kubeconfig
terraform validate
✓ terraform validate - success
terraform plan -out terraform.tfplan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * invalid variable syntax: "internal-tld". If this is part of inline `template` parameter
then you must escape the interpolation with two dollar signs. For
example: ${a} becomes $${a}.
  * invalid variable syntax: "hyperkube-image". If this is part of inline `template` parameter
then you must escape the interpolation with two dollar signs. For
example: ${a} becomes $${a}.
  * invalid variable syntax: "pod-ip-range". If this is part of inline `template` parameter
then you must escape the interpolation with two dollar signs. For
example: ${a} becomes $${a}.
  * invalid variable syntax: "region". If this is part of inline `template` parameter
then you must escape the interpolation with two dollar signs. For
example: ${a} becomes $${a}.
  * invalid variable syntax: "hyperkube-tag". If this is part of inline `template` parameter
then you must escape the interpolation with two dollar signs. For
example: ${a} becomes $${a}.

**Comment by JayBee6** [comment]
was able to solve this issue by installing older version of terraform 0.7.13.  This is because of the breaking changes in terraform 0.8. the below command given in readme is installing the latest 0.8.1 which is not compatible with the variables in this version.
brew update && brew install awscli cfssl jq kubernetes-cli terraform

**Comment by wellsie** [comment]
thanks @JayBee6 

this is fixed now

`brew update && brew install awscli cfssl jq kubernetes-cli terraform` should work
