### ISSUE TITLE
Kibana and logging across namespaces

### ISSUE THREAD

**Issue by ghost** [kz8s/tack#124]
Hey,

Is there any way to use the current Kibana & Elasticsearch setup for logging across multiple namespaces? 

The way I have it working right now is with an extra fluentd daemon set in the default namespace, but maybe there is a better solution.

Thanks :)

**Comment by wellsie** [comment]
hi @vasil-moneybird - what are you looking to log ? docker logs ?

**Comment by ghost** [comment]
Yep
