### ISSUE TITLE
etcd instances all in same AZ?

### ISSUE THREAD

**Issue by erd0s** [kz8s/tack#126]
Is there a reason that all the etcd instances are started in the same AZ? If this is a bug I'd be happy to raise a PR, I guess we'd just need something like `availability_zone = "${ element( split(",", var.azs), count.index ) }"` in [modules/etcd/ec2.tf](https://github.com/kz8s/tack/blob/master/modules/etcd/ec2.tf) right?

**Comment by erd0s** [comment]
Oh sorry @wellsie I just noticed #21, did you end up doing any more research into this?

**Comment by wellsie** [comment]
No worries @erd0s :)

I'm not inclined to run etcd masters across AZs based on what I've read. I'm not so concerned about worker nodes across AZs though. Ultimately federating single az clusters is the way to go for HA

**Comment by erd0s** [comment]
Ah ok @wellsie, thanks for the input!
