### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by cemo** [kz8s/tack#132]
What are the exact steps to create a cluster in aws? I mean which variables I should change to run a cluster? I could not be sure that about this. Should I change io.tf file? Because I have seen some variables on makefile too. What is the proper way to bootstrap a cluster?

**Comment by owenmorgan** [comment]
at a minimum, you can clone this repo and run

`make all `
this will use default variables. you can over ride them in the root Makefile like this.

`make AWS_REGION=eu-west-1 CLUSTER_NAME=my-k8s-cluster all`

**Comment by cemo** [comment]
What about the variables such as `account-id`, `azs`?  I can see some variables empty. What should I do for them?

**Comment by owenmorgan** [comment]
ignore everything outside of the Makefile. That will take care of the other variables.

**Comment by cemo** [comment]
I have just seen necessary configurations. Thanks.
