### ISSUE TITLE
having issue with api server

### ISSUE THREAD

**Issue by cemo** [kz8s/tack#137]
I am making some experiments and have some troubles. I have changed some configurations of api server to enable `cron` resources. I checked `docker ps` and containers are appearing in the list with new process ids. I checked `get nodes` as well and seems normal.

```
$ kubectl get nodes
NAME                                           STATUS                     AGE
ip-10-0-10-10.xx-central-1.compute.internal    Ready,SchedulingDisabled   56d
ip-10-0-10-11.xx-central-1.compute.internal    Ready,SchedulingDisabled   56d
ip-10-0-10-115.xx-central-1.compute.internal   Ready                      56d
ip-10-0-10-12.xx-central-1.compute.internal    Ready,SchedulingDisabled   56d
ip-10-0-10-164.xx-central-1.compute.internal   Ready                      46d
ip-10-0-11-109.xx-central-1.compute.internal   Ready                      56d
ip-10-0-11-218.xx-central-1.compute.internal   Ready                      56d
```

But when I check endpoints I can only see a single endpoint. This seems problematic for me because I am using default configuration and there is 3 master. 

```
$ kubectl get endpoints
NAME              ENDPOINTS        AGE
kubernetes        10.0.10.11:443   56d
```

When I try to access by browser I can see that there is connectivity for them as well. `10.0.10.10` and `10.0.10.12` seems up. 

1. Can someone make a guess why my endpoints are not listed correctly?
2. Which part of the `tack` creates `kubernetes service` in `default` namespace?

Thanks

**Comment by yagonobre** [comment]
1. Probably this the k8s version
2. This [script](https://github.com/kz8s/tack/blob/master/scripts/init-addons) update the templates in `manifests/addons`move this to `.addons` and run `	kubectl create -f .addons/`

**Comment by cemo** [comment]
1. You mean I am using an buggy version which is causing this error? I am using 1.5.1 right now might be better to upgrade latest 1.5.x? 
2. I could not see relevant part in there? There is no add-on about it. What am I referring is this:
```
$ kubectl get service
NAME              CLUSTER-IP   EXTERNAL-IP   PORT(S)          AGE
kubernetes        10.3.0.1     <none>        443/TCP          56d
```
Thanks for your help

**Comment by wellsie** [comment]
@cemo i'm seeing 3 endpoints with the latest drop on master.

```
$ kubectl get endpoints
NAME         ENDPOINTS                                      AGE
kubernetes   10.0.10.10:443,10.0.10.11:443,10.0.10.12:443   38m
```

**Comment by cemo** [comment]
@wellsie there is an issue at my side and see for [details]. I will close this issue since your setup is working properly at k8s 1.6.x. 

[details]: https://github.com/prometheus/prometheus/issues/2543
