### ISSUE TITLE
etcd cloud-config endless loop after failed untis

### ISSUE THREAD

**Issue by jdn-za** [kz8s/tack#17]
Heya :D

Firstly amazing project, <3 your terraform layout big time

I have just started to build with tack, confirmed all pre-req's are correct and on the right versions.

I adjusted the MakeFile to use eu-central-1 and fired it off, no errors as such yet but when it got to about here: `null_resource.verify: Still creating... (1h0m20s elapsed)` I decided it was time to open up the etcd security group to my ip and ssh in and see whats up.

on connect I am greeted with:

`Failed Units: 2
  get-manifests.service
  get-ssl.service`

and I can see the initial process still there

`
 1058 pts/0    Ss+    0:00 /bin/sh /tmp/terraform_1298498081.sh
 1059 pts/0    S+     0:00 /bin/bash -c until curl --silent http://127.0.0.1:8080/version; do sleep 5 && echo .; done
`

Any hints on debugging why/how the cloud-config failed?

Cheers, Jan

**Comment by jdn-za** [comment]
So shame on me for not looking at the closed issues first, my bad ^.^

https://github.com/kz8s/tack/issues/7

proved to helpful with debugging 

```
ip-10-0-0-10 log # systemctl status get-manifests -l
● get-manifests.service - Get kubernetes manifest from s3 bucket using IAM role
   Loaded: loaded (/etc/systemd/system/get-manifests.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2016-06-02 09:31:50 UTC; 1h 2min ago
  Process: 1250 ExecStart=/bin/sh -c /opt/bin/s3-iam-get s3://xxxxxxxxxx-xxx-eu-central-1/manifests/etc.tar | tar xv -C /etc/kubernetes/manifests/ (code=exited, status=2)
  Process: 1248 ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests (code=exited, status=0/SUCCESS)
 Main PID: 1250 (code=exited, status=2)

Jun 02 09:31:50 ip-10-0-0-10.eu-central-1.compute.internal systemd[1]: Starting Get kubernetes manifest from s3 bucket using IAM role...
Jun 02 09:31:50 ip-10-0-0-10.eu-central-1.compute.internal sh[1250]: tar: This does not look like a tar archive
Jun 02 09:31:50 ip-10-0-0-10.eu-central-1.compute.internal sh[1250]: tar: Exiting with failure status due to previous errors
Jun 02 09:31:50 ip-10-0-0-10.eu-central-1.compute.internal systemd[1]: get-manifests.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 02 09:31:50 ip-10-0-0-10.eu-central-1.compute.internal systemd[1]: Failed to start Get kubernetes manifest from s3 bucket using IAM role.
Jun 02 09:31:50 ip-10-0-0-10.eu-central-1.compute.internal systemd[1]: get-manifests.service: Unit entered failed state.
Jun 02 09:31:50 ip-10-0-0-10.eu-central-1.compute.internal systemd[1]: get-manifests.service: Failed with result 'exit-code'.
```

Taking a look at the s3 bucket I can see that he only think there is the `/ssl/k8s-*.tar` part and _no_ `/manifests` was placed

**Comment by jdn-za** [comment]
I see my botocore is a older version than yours though

```
$ aws --version
aws-cli/1.10.5 Python/2.7.10 Darwin/14.5.0 botocore/1.3.27

$ cfssl version
Version: 1.2.0
Revision: dev
Runtime: go1.6.2

$ jq --version
jq-1.5

$ kubectl version --client
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}

$ terraform --version
Terraform v0.6.16
```

**Comment by jdn-za** [comment]
some digging and it looks like boto and eu-central-1 / s3 dont play nicely 

https://github.com/boto/boto/issues/2741

**Comment by jdn-za** [comment]
found it

```
module.s3.aws_s3_bucket.ssl (local-exec): usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
module.s3.aws_s3_bucket.ssl (local-exec):        mktemp [-d] [-q] [-u] -t prefix
module.s3.aws_s3_bucket.ssl (local-exec): ✗ Error from s3-cp on line 52!
```

TMP=$(mktemp -d) to TMP=$(mktemp -d tmpp)

```
TMP=$(mktemp -d)
trap cleanup EXIT
cp $MANIFESTS/* $TMP
sed -i.bak 's|${HYPERKUBE}|'"$HYPERKUBE|g" "$TMP/"*.yml
```

Just dirty forcing of making the tmp dir, but it worked. Will pr when further along

**Comment by wellsie** [comment]
Hey @jdn-za. Glad you like the terraform layout !! Also glad you worked out your issue. What os you running terraform on ?

I apologize, after the fact, for the hackiness around the s3 bucket provisioning. It has been the cause of several opaque issues :( I will be working on addressing this over the next few weeks. At the very least better messaging around what is happening and where to look for more information. Most likely though I will create a terraform plugin that will streamline not just the s3 provisioning but the rest of the 'non-terraform' stuff happening in the makefile.

looking forward to the pr.

**Comment by jdn-za** [comment]
Running on OSX 10.10.5, I do have a huge layer of crud on this machine though. just did a fresh install of Ubuntu 14.04 LTS to another laptop and will see if I run into similar issues.

Im busy exploring adding in some of my terraform modules to describe EC2 specific auxiliary services we would want inside the vpc but not part of kubernetes cluster itself.

Dont apologize mate! its the best starting point I have seen yet :)

Also going to look to get eh etcd running multi AZ and probably a second Bastion. Many more ideas to come
