### ISSUE TITLE
Add a new etcd member to the cluster?

### ISSUE THREAD

**Issue by tomfotherby** [kz8s/tack#196]
We want to use the Kubernetes `CronJob` directive. It's in alpha so we wanted to change the kube-apiserver runtime-cofig to add:

    batch/v2alpha1=true

We updated `modules/etcd/cloud-config.yml` and what we should have done to have it applied is, stop each instance, update the `user-data` via the aws console and start each instance again, one-at-a-time. But unfortunatly, we mistakenly terminated 1 etcd instance and then ran terraform to re-create it. This mean that certs changed on the new instance. The kubernetes cluster is healthy but the etcd cluster isn't healthy. I'm not sure how to add the new node back to the etcd cluster, does anyone know how to do it?

From a existing etcd node:

    $etcdctl cluster-health
    member 4600cb0782ea3f3a is healthy: got healthy result from https://etcd1.test.k8s:2379
    member da005d6249a28694 is healthy: got healthy result from https://etcd2.test.k8s:2379
    cluster is healthy

From the new etcd node:

    $ etcdctl cluster-health
    cluster may be unhealthy: failed to list members
    Error:  client: etcd cluster is unavailable or misconfigured
    error #0: client: endpoint https://etcd3.test.k8s:2379 exceeded header timeout

**Comment by cemo** [comment]
Did you see something unusual in `journalctl` ?

**Comment by tomfotherby** [comment]
Yes, there is something interesting:

> member 503c0bbb246020af has already been bootstrapped

In full:

```
Jun 23 13:27:46 ip-10-56-0-22.ec2.internal etcd-wrapper[15194]: 2017-06-23 13:27:46.379307 I | etcdmain: stopping listening for client requests on 0.0.0.0:2379
Jun 23 13:27:46 ip-10-56-0-22.ec2.internal etcd-wrapper[15194]: 2017-06-23 13:27:46.379407 I | etcdmain: stopping listening for peers on https://0.0.0.0:2380
Jun 23 13:27:46 ip-10-56-0-22.ec2.internal etcd-wrapper[15194]: 2017-06-23 13:27:46.379437 C | etcdmain: member 503c0bbb246020af has already been bootstrapped

Jun 23 13:27:47 ip-10-56-0-22.ec2.internal systemd[1]: etcd-member.service: Main process exited, code=exited, status=1/FAILURE
Jun 23 13:27:47 ip-10-56-0-22.ec2.internal systemd[1]: Failed to start etcd (System Application Container).
Jun 23 13:27:47 ip-10-56-0-22.ec2.internal systemd[1]: etcd-member.service: Unit entered failed state.
```

I tried removing the data-dir with

    $ sudo rm -rf /var/lib/etcd/       

and retrying. No luck

Since I don't know what I'm doing I tried other random things like:

    $ sudo systemctl start etcd2

and

    $ sudo systemctl start etcd-member

No luck.

**Comment by tomfotherby** [comment]
I will close this. It's a bit niche. The correct thing next time I need to update some user-data is to do do it via the web-console and then just reboot the etcd member, not terminate it.
