### ISSUE TITLE
Can hyperkube run solely on rkt?

### ISSUE THREAD

**Issue by bensonz** [kz8s/tack#203]
I am just curious that can we run hyperkube solely (kubelet and etc) on rkt?
Since there is already a step for prefetch-rkt-hyperkube.service, which pulls a hyperkube image into rkr. Why is there also prefetch-docker-hyperkube.service step? 
Why do we need the docker hyperkube image?

**Comment by wellsie** [comment]
good question. kubernetes components like apiserver also use hyperkube:
https://github.com/kz8s/tack/blob/master/modules/etcd/cloud-config.yml#L236
