### ISSUE TITLE
3 Weird issues after DNS didnt resolve hasicorp

### ISSUE THREAD

**Issue by cmarquezrusso** [kz8s/tack#209]
Hi,

I was trying to deploy a new cluster and I got these issues after "make all"

> Error installing provider "template": Get https://releases.hashicorp.com/terraform-provider-template/: dial tcp: lookup releases.hashicorp.com on 10.100.0.1:53: read udp 10.100.10.4:59968->10.100.0.1:53: i/o timeout.

This was related to my ISP's DNS server. I switched out to use Google ones and this continued... until this one appeared:

> An error occurred (InvalidKeyPair.Duplicate) when calling the CreateKeyPair operation: The keypair 'kz8s-connect' already exists.
> make: *** [.keypair/kz8s-connect.pem] Error 255

I tried again on a clean directory, cloning the repo and still.

My coworker ran this on his computer and it worked. He built and destroyed the cluster successfully.

I updated all the brew packages.

Current error is this:

```
* module.pki.provider.aws: Not a valid region: ap-southeast-2
* module.iam.provider.aws: Not a valid region: ap-southeast-2
* module.security.provider.aws: Not a valid region: ap-southeast-2
* module.route53.provider.aws: Not a valid region: ap-southeast-2
* module.s3.provider.aws: Not a valid region: ap-southeast-2
* module.worker.provider.aws: Not a valid region: ap-southeast-2
* module.vpc.provider.aws: Not a valid region: ap-southeast-2
* module.etcd.provider.aws: Not a valid region: ap-southeast-2
* module.bastion.provider.aws: Not a valid region: ap-southeast-2
```

Do you have any idea about what can be going on?

**Comment by yagonobre** [comment]
You coworker build the cluster in the `ap-southeast-2` region?

**Comment by ikhripunov** [comment]
I'm the named coworker. Yes, I've been building and tearing down cluster in `ap-southeast-2`

**Comment by cmarquezrusso** [comment]
**Update**: I tried 3 tests changing the cluster name and it worked. It seems that there is/are some exisiting resources on AWS that were created by `make all` and were not deleted by `make clean` because the cluster wasn't ready.

Is there any `make clean` to delete exisiting AWS resources without checking locally?

The scenario is:

1. git clone tack
2. Modify makefile
3. Running `make clean` will delete exisiting resources on AWS.

I think this may depend on Terraform init though.
