### ISSUE TITLE
OutOfService Load Balancers

### ISSUE THREAD

**Issue by jtfogarty** [kz8s/tack#212]
All 3 load balancers have a status of OutOfService with the error;

`Instance has failed at least the UnhealthyThreshold number of health checks consecutively.`

Here are the versions I'm using

awscli 1.14.20
cfssl 1.2.0_2
jq 1.5_2
kubernetes-cli 1.9.1 
terraform 0.11.2 

Any ideas on what is causing this or how to troubleshoot? 
Thanks

Jeff

**Comment by yamaszone** [comment]
I am seeing the same issue. Here are the versions of my stack:
- CoreOS 1576.5.0 (ami-dc4ce6a4, stable, hvm)
- etcd 3.2.9
- Docker 17.09.0
- rkt 1.29.0
- hyperkube v1.7.4_coreos.0
- Terraform 0.10.2
- cfssl 1.2.0
- awscli 1.11.138
- jq 1.5

As a result, there's a infinite loop for "❤ Curling apiserver external elb..............."

@wellsie Any ideas? Thanks in advance for help.

**Comment by dionjwa** [comment]
I tried changing the instance types to no avail in `io.tf`:
```
    bastion = "t2.micro"
    pki = "t2.micro"
    etcd = "m4.large"
    worker = "m4.large"
```

**Comment by LucasR93** [comment]
Same problem. Did you find a solution?

**Comment by lucasreiners** [comment]
Finally found the solution:

add the line:
`Environment="ETCD_IMAGE_TAG=v3.1.11"` under 

```yaml
- name: 10-environment.conf
          content: |
            [Service]
            Environment="ETCD_IMAGE_TAG=v3.1.11"
```


to worker/cloud-config.yml and etcd/cloud-config.yml

**Comment by mzhaase** [comment]
I think this is due to the fact that the ELB is in the public subnet: tack/modules/etcd/elb.tf:24 but it tries to attach to the etcd nodes which run in the private subnet: tack/modules/etcd/ec2.tf:17

**Comment by yamaszone** [comment]
The same solution mentioned in @LucasR93's post worked for me; I tried with etcd `v3.1.6` though. The existing deployment seems not compatible with etcd `v3.2.0+`. I am yet to dig into why deployment fails with latest etcd. In the meantime, the etcd version should be pinned down to `v3.1.X` to prevent users of this repo encountering a broken cluster deployment.

@wellsie would you like to get a PR with the etcd version pinned down until compatibility is restored for latest version?
