### ISSUE TITLE
s3-iam-get return nothing (eu-central-1)

### ISSUE THREAD

**Issue by pixeleet** [kz8s/tack#25]
I have verified that the files exist on S3 and downloading the very same tar and extracting it yields the correct files, yet with the profile assigned the manifests and the addons are never downloaded from S3 and thus the setup never finishes properly.

region = "eu-central-1"
ami = "ami-7b7a8f14" CoreOS-stable-1068.8.0-hvm

**Comment by wellsie** [comment]
can you ssh into an etcd box (`make ssh`) and then do a `systemctl` ?

**Comment by pixeleet** [comment]
It’s the signature version, seems that eu-central-1 uses v4 and eu-west-1 still uses v3 so it’s an issue of s3-iam-get.

Opened an issue there. https://github.com/kz8s/s3-iam-get/issues/1 https://github.com/kz8s/s3-iam-get/issues/1

**Comment by wellsie** [comment]
@pixeleet - i've throw together a pre-signed url generator:
https://github.com/kz8s/s3-get-presigned-url

i've checked that this works in `eu-central-1`.

would you mind verifying that this fixes your issue? code is on branch [issue-25](/kz8s/tack/tree/issue-25)

**Comment by pixeleet** [comment]
Just ran it. Worked like a charm ;) 

Good job man! It's super helpful as we're migrating away from ECS and this just saved me a ton of time :) 👍

**Comment by wellsie** [comment]
You're welcome !! Always 'extra' happy to help someone move off of ECS too
