### ISSUE TITLE
Front Facing Load Balancer

### ISSUE THREAD

**Issue by pixeleet** [kz8s/tack#27]
Hey @wellsie 

Did you already think about a front-facing load balancer implementation? 
I'm not happy with declaring `Type`: `LoadBalancer` as it will create a new one for each service.

Did you try the [NGiNX Ingress Controller](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx) already? [Deis-Router](https://github.com/deis/router)? 

I'll be experimenting a bit today, but would be curious if you already did come up with a solution on this.

Cheers,
David

**Comment by wellsie** [comment]
I've been leaning towards nginx ingress controller; but haven't done any experimenting yet. Am interested to hear your thoughts.

**Comment by pixeleet** [comment]
I have tried deis's router today, but I'm not entirely happy with the magic happening there, for instance the service **has** to expose port 80 to be considered for routing, and it wasn't properly documented, and while in their product _Workflow_ this is handled by the deis-controller, if you're not opting for the whole package but the router only, there is some magic to cover by hand. 

I'll try the nginx ingress controller tomorrow and will let you know my findings.

cheers,
David

**Comment by pixeleet** [comment]
@wellsie 

I've tried the `deis/router` and the `nginx-ingress-controller` from the kube team. 
Both pretty much work the same way, the only problem I have with the normal `nginx-ingress-controller` is that it doesn't fare very well with upstreams not being present or launching still.

So I can foresee a situation where your ELBs start detaching istances because NGiNX starts dying and suddenly you can't conduct proper health checks.

Other than that, both solutions work pretty much the same way, you just configure them in different places.

**Comment by rokka-n** [comment]
Did it work for nodes in private networks?
