### ISSUE TITLE
CoreOS Stable AMI's deregistered / unavailable (eu-central-1 and others)

### ISSUE THREAD

**Issue by pixeleet** [kz8s/tack#31]
Hey @wellsie 

Not sure if this affects other AZs but CoreOS AMI discovery is broken on eu-central-1. 
The AMI ID being found is non accessible as a public AMI.

What could have changed?

Cheers,
David

**Comment by wellsie** [comment]
upstream issue affecting multiple regions:
https://github.com/coreos/bugs/issues/1509

> We cannot proceed with your requested configuration. You cannot use this AMI (ami-3ae31555).
> This AMI has been deregistered, or you do not have permission to use it. Try again with another AMI for which you have permissions, or request permission to use this AMI from its owner.

![screen shot 2016-08-10 at 6 56 11 am](https://cloud.githubusercontent.com/assets/5160593/17556365/019cb110-5ec8-11e6-8aa3-7a01dd933a12.png)

**Comment by wellsie** [comment]
fixed upstream
