### ISSUE TITLE
Error refreshing state

### ISSUE THREAD

**Issue by guiocavalcanti** [kz8s/tack#45]
After running `make all` and `make clean`, when I run `make all` again I receive this error:

```
Error refreshing state: 1 error(s) occurred:

* aws_route.public: Error while checking if route exists: InvalidRouteTableID.NotFound: The routeTable ID 'rtb-074fae63' does not exist
        status code: 400, request id: ed09f4b3-9e42-4729-9577-dfac5700398e
```

[Here](https://gist.github.com/guiocavalcanti/ba5878a46696c81d009ed0c91a56dc9f) you can see the complete log.

**Comment by guiocavalcanti** [comment]
Maybe related with https://github.com/hashicorp/terraform/issues/7104

**Comment by guiocavalcanti** [comment]
I cherry-picked https://github.com/kz8s/tack/commit/fb3d0a5f30ef9e84ecf6ca4a064bbb4150bfb38f and switched do 0.7.1 and the error still occurs.

**Comment by wellsie** [comment]
for transient errors with terraform like this one, simply running `make all` will often get cluster spin up moving again.

fyi - will be moving [master](https://github.com/kz8s/tack/tree/master) to terraform 0.7.1 today.

**Comment by guiocavalcanti** [comment]
@wellsie running multiple times didn't solve the problem =/

**Comment by wellsie** [comment]
@guiocavalcanti can you try with the latest [master](https://github.com/kz8s/tack/tree/master)? I wouldn't have expected cherry picking  https://github.com/kz8s/tack/commit/fb3d0a5f30ef9e84ecf6ca4a064bbb4150bfb38f to work given the differences between the branches.

**Comment by guiocavalcanti** [comment]
@wellsie you are right! but the error still occurs. Do you think this https://github.com/hashicorp/terraform/issues/5288  recently closed issue solves the problem?

**Comment by guiocavalcanti** [comment]
@wellsie I compiled with that commit and the error still occurs. Any ideias?

**Comment by wellsie** [comment]
Can you try cloning tack to a new directory. In the makefile change the region to somewhere different from you last attempts and try 'make all' from there ? Lmk how it goes.

**Comment by idris** [comment]
@guiocavalcanti did you ever get this resolved?  I'm currently getting the `InvalidRouteTableID.NotFound` no matter what I do, even during `terraform destroy`

**Comment by yagonobre** [comment]
@idris you can see the route table in aws console?

**Comment by idris** [comment]
@yagonobre no, the route is gone.  I just want to `terraform destroy`, but this blocks it

**Comment by yagonobre** [comment]
run `grep aws_route terraform.tfstate`

**Comment by idris** [comment]
@yagonobre 

```
                "aws_route.external": {
                    "type": "aws_route",
                        "aws_route_table.external"
                "aws_route.internal.0": {
                    "type": "aws_route",
                        "aws_route_table.internal"
                "aws_route.internal.1": {
                    "type": "aws_route",
                        "aws_route_table.internal"
                "aws_route.internal.2": {
                    "type": "aws_route",
                        "aws_route_table.internal"
                "aws_route.internal.3": {
                    "type": "aws_route",
                        "aws_route_table.internal"
                "aws_route_table.external": {
                    "type": "aws_route_table",
```

**Comment by yagonobre** [comment]
Try `terraform refresh && terraform destroy`

**Comment by idris** [comment]
FYI my issue was fixed here: https://github.com/hashicorp/terraform/pull/9431
