### ISSUE TITLE
post creation - adding a worker of a different AWS instance type

### ISSUE THREAD

**Issue by nkhine** [kz8s/tack#51]
Hi,
I have setup a cluster with 3 masters and 3 workers, now I want to add additional 3 workers to the cluster with a different AWS instance type in order to run mongodb on these, what is the correct way to do this?

Any advise is much appreciated.

**Comment by wellsie** [comment]
i would copy the [worker module](https://github.com/kz8s/tack/blob/master/modules.tf#L115-L132) entry in `modules.tf`. rename the copy to say `module "worker2"` and then change the `instance-type` as desired.

this will create another ASG of workers.

to apply the changes to the running cluster:

```
make apply
```
