### ISSUE TITLE
 dial unix /var/run/fleet.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by nkhine** [kz8s/tack#54]
running 

```
core@ip-10-0-0-11 ~ $ fleetctl status 
Error retrieving unit: Get http://domain-sock/fleet/v1/units?alt=json: dial unix /var/run/fleet.sock: connect: no such file or directory
core@ip-10-0-0-11 ~ $ 
```

**Comment by wellsie** [comment]
This would most likely be because fleet is not turned on. I don't turn it
on because it is not needed for k8s. You could add a fleet section to the
cloud configs if you need / want it:

https://coreos.com/os/docs/latest/cloud-config.html
