### ISSUE TITLE
On Vagrant `make all` gives "/bin/sh: 1: [[: not found"

### ISSUE THREAD

**Issue by matthewvalimaki** [kz8s/tack#63]
Created myself a Vagrant box where `tack` is on `/vagrant`. With AWS region set to "west" and after executing `make all` I saw the following:

```
✓ make apply - success
✓ terraform portion of 'make all' has completed 
make .addons
make[1]: Entering directory '/vagrant'
/bin/sh: 1: [[: not found
❤ commence initializing addons 
❤ Polling for cluster life - this could take a minute or more
```

**Comment by wellsie** [comment]
can you share the vagrant box definition you are using ?

this looks like a shell isssue. try changing this section in the `Makefile`:

```
.addons:
    @[[ -d $@ ]] || \
        echo "${BLUE}❤ commence initializing addons ${NC}" && ./scripts/init-addons
```

to:

```
.addons:
    @[ -d $@ ] || \
        echo "${BLUE}❤ commence initializing addons ${NC}" && ./scripts/init-addons
```

note the single '[' ']'. coming to think of it `[[ -d $@ ]]` is redundant and can probably be removed. i'll check into that later and post a fix.

**Comment by matthewvalimaki** [comment]
> can you share the vagrant box definition you are using ?

Vagrantfile attached.
[Vagrantfile.txt](https://github.com/kz8s/tack/files/464479/Vagrantfile.txt)

> try changing this section in the

Great success! So that indeed fixed it for me.
