### ISSUE TITLE
make clean does not remove generated files

### ISSUE THREAD

**Issue by matthewvalimaki** [kz8s/tack#64]
Readme says this about `make all`: "To destroy, remove and generally undo everything". However it would seem that file such as `terraform.tfvars` is not deleted and is not re-generated next time I do `make all`. For example if I change AWS region while mentioned file exists the change is not applied.

Perhaps the reason to keep this and other files is for safety, just in case attempt to remove resource fails. But if Terraform comes back with "Destroy complete!" could we assume all is good?

**Comment by wellsie** [comment]
hi. the readme says that about `make clean`.

Here is the `clean` goal:

```
## destroy and remove everything
clean: destroy delete-keypair
    pkill -f "kubectl proxy" ||:
    rm -rf .addons ||:
    rm terraform.{tfvars,tfplan} ||:
    rm -rf .terraform ||:
    rm -rf tmp ||:
    rm -rf ${DIR_SSL} ||:
```

It does the following in this order:
- `terraform destroy`
- remove the ec2 keypair
- kill the `kubectl proxy` if it is running
- remove the `.addons/` directory
- remove `terraform.tfvars` and `terraform.tfplan`
- remove the `.terraform/` directory
- remove the `tmp/` directory
- remove the `.cfssl/` directory

are running `make clean` ? i spin up and tear down several clusters an hour and am not seeing a problem.

**Comment by matthewvalimaki** [comment]
Perhaps it doesn't work for me because of this:

```
Destroy complete! Resources: 66 destroyed.
# todo: rework this delete logic
aws --region us-west-2 ec2 delete-key-pair --key-name k8s-testing || true
ssh-add -L | grep ".keypair/k8s-testing.pem" > .keypair/k8s-testing.pub || true
Could not open a connection to your authentication agent.
if [ -s .keypair/k8s-testing.pub ]; then \
    ssh-add -d .keypair/k8s-testing.pub; \
fi;
pkill -f "kubectl proxy" ||:
Makefile:57: recipe for target 'clean' failed
make: *** [clean] Terminated
```

Should've posted that too earlier. Sorry.

**Comment by wellsie** [comment]
can you remove this line from the `Makefile` and try again?:
`pkill -f "kubectl proxy" ||:`

What os are you running on ?

**Comment by matthewvalimaki** [comment]
Tried:

```
# todo: rework this delete logic
aws --region us-west-2 ec2 delete-key-pair --key-name k8s-testing || true
ssh-add -L | grep ".keypair/k8s-testing.pem" > .keypair/k8s-testing.pub || true
Could not open a connection to your authentication agent.
if [ -s .keypair/k8s-testing.pub ]; then \
    ssh-add -d .keypair/k8s-testing.pub; \
fi;
rm -rf .addons ||:
rm terraform.{tfvars,tfplan} ||:
rm: cannot remove 'terraform.{tfvars,tfplan}': No such file or directory
rm -rf .terraform ||:
rm -rf tmp ||:
rm -rf .cfssl ||:
```

It says no such file or dir but both tfvars and tfplan exist.

> What os are you running on ?

Ubuntu 16.04
