### ISSUE TITLE
Stuck on "Curling apiserver external elb"

### ISSUE THREAD

**Issue by matthewvalimaki** [kz8s/tack#65]
This might be bit of on the support side than an issue side, feel free to close it if so. I am not familiar with `tack` scripts or AWS really.

Fresh after cloning `tack`, setting AWS region to `us-west-2` and running `make clean` I get to "Curling apiserver external elb" which then goes on indefinitely. Looking at Load Balancers on EC2 Management I see that the LB has 3 instances (etcd1/2/3-k8s-testing) and all are being reported having status "OutOfService".
1. Any ideas why they are "OutOfService" and is this something I should manually fix?
2. Could we add checks to the status and then try to fix it or suggest how to fix it manually?

**Comment by wellsie** [comment]
sorry for the delay. i have not seen this issue before. it does take some time for the instances to come online. are you still seeing the issue?
