### ISSUE TITLE
Correct way to add new worker nodes that are different instance type?

### ISSUE THREAD

**Issue by nkhine** [kz8s/tack#68]
Hello,
I would like to add additional worker nodes, but these to be of a different EC2 instance type, what is the correct way to achieve this?
Would `terraform plan` and `terraform apply` after creating the worker type?
Any advice much appreciated.

**Comment by wellsie** [comment]
take a look at the commits from #72 
- create a new worker module (make sure it's `worker-name` is unique)

only needed if you are modifying an existing cluster:
- `terraform get`
- `terraform apply`

**Comment by adambom** [comment]
You may find this useful as well: http://kubernetes.io/docs/user-guide/node-selection/
