### ISSUE TITLE
Gets stuck at null_resource.initialize: Still creating... 

### ISSUE THREAD

**Issue by ndbroadbent** [kz8s/tack#7]
Hi, firstly thanks for creating this, it's an awesome resource!

I'm just having some trouble getting it to work. When I SSH to 10.0.0.10, I see this:

```
Failed Units: 1
  get-manifests.service
```

I probably screwed it up by trying to limit the number of servers, because I'm still waiting for AWS to increase my instance limit (currently at 5). I also don't need that much capacity right now, so would like to run just 1 worker, and 1 etcd server. So I made the following changes:

```
variable "etcd-ips" { default = "10.0.0.10" }
```

and I set `desired_capacity` to `1`.

Is that what might be causing problems?

**Comment by wellsie** [comment]
Hi Nathan. Glad this is useful ;) 

I hadn't tried one etcd instance until this morning - it worked ok for me.

The `get-manifests.service` is responsible for fetching content from the s3 bucket we create. It shouldn't be affected by limiting the number of machines.

What does `systemctl status get-manifests -l` show on `10.0.0.10`? 

You can also try to manually run the steps in `get-manifests.service` to get more insight:

```
# check these directories exist
#/usr/bin/mkdir -p /etc/kubernetes/manifests
#/usr/bin/mkdir -p /srv/kubernetes/manifests

/bin/sh -c "/opt/bin/s3-iam-get ${ etc-tar } | tar xv -C /etc/kubernetes/manifests/"
/bin/sh -c "/opt/bin/s3-iam-get ${ srv-tar } | tar xv -C /srv/kubernetes/manifests/"
```

Your copy of the `get-manifests.service` will have your values for `${ etc-tar }` and `${ srv-tar }`.

lmk what you find out - this should be fairly easy to diagnose and fix :)

**Comment by ndbroadbent** [comment]
Hey thanks for the help! I just noticed this error in the output, from `s3-cp`: 

```
sed: can't find label for jump to `ak'
```

Really not sure why that's happening, but it seemed to be fixed when I changed the sed commands to:

```
sed -i 'bak' 's|${HYPERKUBE}|'"$HYPERKUBE|g" "$TMP/"*.yml
sed -i 'bak' 's|${PODMASTER}|'"$PODMASTER|g" "$TMP/"*.yml
```

FWIW I have `gnu-sed` installed on my Mac.

**Comment by ndbroadbent** [comment]
Whoops, no I forgot to reinstall `gnu-sed` before testing the change. The actual fix was just changing `-i bak` to `-ibak`:

```
sed -ibak 's|${HYPERKUBE}|'"$HYPERKUBE|g" $TMP/*.yml
```

Works on both sed versions.

**Comment by wellsie** [comment]
Thanks Nathan. The error function (b8b590babc3c4b8264fd9ccaa97a0f92e526f6db) helps a lot ;)
