### ISSUE TITLE
Unable to access dashboard from elb

### ISSUE THREAD

**Issue by owenmorgan** [kz8s/tack#70]
Hello. After a fresh build, I'm unable to access the dashboard from the ELB

Https://{ELB}/ui 

Gives "Unorthorized" response

**Comment by wellsie** [comment]
see #65

**Comment by owenmorgan** [comment]
All instances on the ELB are in service

**Comment by wellsie** [comment]
sorry #69

**Comment by owenmorgan** [comment]
I can access the dashboard after kubectl proxy on localhost. But not through the ELB

**Comment by wellsie** [comment]
https://github.com/kubernetes/dashboard/issues/574
