### ISSUE TITLE
Unable to view Grafana

### ISSUE THREAD

**Issue by owenmorgan** [kz8s/tack#74]
From uncommenting the "type: LoadBalancer" from "grapfana-service.yaml" and running

$ kubectl create -f deploy/kube-config/influxdb/

Everything loads ok, and I'm able to see metrics on the Dashboard. But hitting the ELB thats created for Grafana, I see the below.

image
![image](https://cloud.githubusercontent.com/assets/10656664/18880683/a5e3fcdc-84d0-11e6-89de-71b20c0c8942.png)

access log on the pod shows.

> 2016-09-27T07:58:40.336230046Z 2016/09/27 07:58:40 [I] Completed 10.2.96.0 - "GET /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/public/app/app.ca0ab6f9.js HTTP/1.1" 404 Not Found 23 bytes in 403us

**Comment by guiocavalcanti** [comment]
@owenmorgan there's some problem loading static files. Try to run `kubectly proxy` and access localhost:8001/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana

**Comment by jaigouk** [comment]
I was able to install deis with grafana
