### ISSUE TITLE
AWS Auto Scaling Policy

### ISSUE THREAD

**Issue by yagonobre** [kz8s/tack#76]
Tack suport Scaling UP/Down Policy?

**Comment by owenmorgan** [comment]
it creates an ASG, but no Scaling Policies

**Comment by yagonobre** [comment]
If I create the scaling polices, this will work?

**Comment by owenmorgan** [comment]
Yes. If you make it in terraform, please share

**Comment by yagonobre** [comment]
I will submit a PR
