### ISSUE TITLE
Question: usable as a terraform module? or does this require calling the makefile independently

### ISSUE THREAD

**Issue by kvey** [kz8s/tack#79]
Is this project usable as a terraform module? 
Or does this require calling the makefile independently.
Wondering how easy or hard this is to keep with including this in the rest of my terraform config, versus managing this portion of infrastructure from/as a separate repo.

**Comment by wellsie** [comment]
yes `tack` can theoretically be used as a terraform module. the inputs and outputs are defined in `io.tf` in the root directory. be aware though that some of the modules 'expect' things to be in certain places - ie certificates for ssl. i am actively working on relaxing those requirements.

**Comment by kvey** [comment]
Thanks! Wanted to confirm before getting into that.

**Comment by kvey** [comment]
Fails to get the AMI ID - due to skipping the makefile I expect - do you have any recommendations for fixing this?

My solution in this case would probably be to just set it to an actual var on my end since I can assume everything the makefile is otherwise trying to determine?

Overall the makefile is doing quite a lot, I think not making it really viable to purely use this as a module?
I suppose the alternative is run the makefile with appropriate settings - then terraform get - then use as module
