### ISSUE TITLE
Losing connection while running kubectl exec and logs

### ISSUE THREAD

**Issue by guiocavalcanti** [kz8s/tack#80]
Since Kubernetes 1.3.7 I loose connection while running commands like `kubectl exec -it pod -- /bin/bash` after 1 minute idle.

The same problem occurs when using `kubectlg logs -f pod-name`.

Any ideia on what can be causing this?

**Comment by wellsie** [comment]
Yep - this is almost certainly due to the default timeout on the public apiserver ELB. the timeout can be extended up to 3600 seconds. I am testing 3600 as the default value now. I will update master later if everything checks out ok.

**Comment by guiocavalcanti** [comment]
@wellsie hey, that makes sense! thank you!
