### ISSUE TITLE
use a different cidr ip range

### ISSUE THREAD

**Issue by nkhine** [kz8s/tack#87]
I tried to use the alternate IP by uncommenting https://github.com/kz8s/tack/blob/master/Makefile#L38-L42 but it seems there are some hard coded https://github.com/kz8s/tack/blob/effca18db0868b24fc30f017af077c3dbbbb2cae/modules/vpc/public.tf#L17 to 10.0

what is the correct way to use a different cidr ip block range?

**Comment by yagonobre** [comment]
Uncommenting this lines, you change the cidr ip block used by kubernetes. You need to change K8S_SERVICE_IP and K8S_DNS_IP for the CIDR_SERVICE_CLUSTER range.
This [`file`](https://github.com/kz8s/tack/blob/effca18db0868b24fc30f017af077c3dbbbb2cae/modules/vpc/public.tf#L17) refer to [vpc cidr](https://github.com/kz8s/tack/blob/master/Makefile#L32), and I think it is hard coded.

**Comment by yagosantos** [comment]
I'm fixing it, I Will submit a pr later.

**Comment by yagonobre** [comment]
I'm fixing it

**Comment by wellsie** [comment]
thx @yagonobre - merged
