### ISSUE TITLE
Autoscaling Policy

### ISSUE THREAD

**Issue by adambom** [kz8s/tack#99]
When load is high, the worker group should scale up. When load is low it should scale down. I've written some configuration that uses cloudwatch alarms to trigger autoscaling policies based on Average CPU Utilization and Memory Utilization.
- Average CPU Utilization > 80% => Add node
- Average Memory Utilization > 80% => Add node
- Average CPU Utilization < 40% => Remove node
- Average Memory Utilization < 40% => Remove node

Cooldown 300 seconds.

The memory utilization metric requires running some code on the hosts, but I've integrated it with cloud-config.

Is there any interest in adding this functionality to Tack? If so I'm happy to submit a PR for discussion. There's definitely room for improvement in the policies themselves, but it's a good starting point.

**Comment by rimusz** [comment]
yes, please

**Comment by wellsie** [comment]
added https://github.com/kubernetes/autoscaler
